default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: anton_dms_development
  username: anton_dms
  password: password
  host: localhost
  port: 5432

test:
  <<: *default
  database: anton_dms_test

production:
  <<: *default
  database: anton_dms_production
  username: anton_dms
  password: <%= ENV['ANTON_DMS_DATABASE_PASSWORD'] %>
